// Usurpia Lens Bookmarklet - V2.6 (The "Guided Analyst" Model)
// Implements "Analysis Modes" for guided learning and "Dialectic Mode" for intellectual self-defense.

(function() {

    // --- CONFIGURATION & FORTIFIED DICTIONARY ---
    const config = {
        settings: {
            maxHighlights: 15,
            initialAnalysisMode: 'engine', // 'engine', 'institutions', 'full'
            initialDialecticMode: false // true or false
        },
        dictionary: {
            core: {
                name: "The Engine",
                words: [
                    { terms: ["economic growth", "growth", "growing pie"], primaryTerm: "economic growth", explanations: { headline: "Mandatory Expansion", summary: "The system's core imperative. It must expand exponentially to service the interest on past debt, chaining a mathematical function to a finite planet, which guarantees a future collision.", defense: "System Defense: Dismissed as being 'anti-progress.' This is the 'Solution Fallacy,' demanding a perfect alternative before a valid diagnosis can be made." } },
                    { terms: ["debt", "indebtedness"], primaryTerm: "debt", explanations: { headline: "The Tool of Control", summary: "Presented as a tool for commerce, its primary function in this system is control. Perpetual indebtedness ensures compliance, transfers power, and compels participation in the 'Competition Trap'.", defense: "System Defense: Portrayed as a neutral tool for opportunity. This ignores that its systemic structure (interest-bearing, created by private banks) makes it a mechanism of control, not liberation." } },
                    { term: "interest", explanations: { headline: "The Extraction Engine", summary: "The 'something for nothing' charge that powers wealth extraction from the real economy and mathematically necessitates the 'Mandatory Expansion'.", defense: "System Defense: Justified as 'the price of risk.' This ignores that the creditor risks little when they can create the money out of nothing and are backstopped by the government." } },
                    { term: "usury", explanations: { headline: "The Ancient Poison", summary: "The ancient term for lending money at interest, which was historically contained as a social poison before being rebranded as 'progress' to create the modern system.", defense: "System Defense: Dismissed as an archaic, irrelevant religious term. This is a deliberate historical erasure to obscure the fact that the system's engine was once universally recognized as toxic." } },
                    { term: "inequality", explanations: { headline: "A Feature, Not a Bug", summary: "The guaranteed mathematical outcome of a system where compounding interest systemically funnels wealth from debtors (the majority) to creditors (the few).", defense: "System Defense: Blamed on individual failings or 'globalization.' This is the 'Appeal to Complexity,' creating a fog to hide the simple, mathematical driver of wealth divergence." } }
                ]
            },
            institutional: {
                name: "Institutional Capture",
                words: [
                    { terms: ["Federal Reserve", "The Fed", "central bank"], primaryTerm: "Federal Reserve", explanations: { headline: "The Creditors' Cartel", summary: "A private banking cartel with a public mandate. Its primary function is not to serve the public, but to manage the stability and profitability of the debt-based system for its member banks.", defense: "System Defense: Portrayed as a necessary, objective manager of the economy. This is the 'Technocracy' argument, designed to make the system's control seem too complex for democratic debate." } },
                    { terms: ["politician", "lawmaker", "government"], primaryTerm: "politician", explanations: { headline: "The System Manager", summary: "An actor in the political theater, primarily tasked with managing public discontent and passing legislation that serves the interests of the system's main beneficiaries (their donors).", defense: "System Defense: The focus is kept on partisan battles. This is a primary distraction, making people fight over the 'managers' while the system's owners and rules remain unchallenged." } },
                    { term: "lobbying", explanations: { headline: "Systemic Bribery", summary: "The mechanism through which concentrated wealth, generated by the debt-engine, captures the political process. It ensures that laws protect and enhance the system, creating a feedback loop of power.", defense: "System Defense: Defended as 'free speech' and 'petitioning the government.' This sanitizes the reality that it makes political power a direct function of money, subverting democracy." } },
                    { term: "GDP", explanations: { headline: "Gross Destruction Product", summary: "The system's primary metric of 'progress.' A flawed number where pollution, clear-cutting a forest, and building prisons are all counted as economic positives, perfectly revealing the system's perverse values.", defense: "System Defense: Defended as the best measure we have. This is institutional inertia, refusing to adopt metrics (like Genuine Progress Indicator) that would expose the system's destructive nature." } }
                ]
            },
            societal: {
                name: "Societal & Cultural",
                words: [
                    { term: "the economy", explanations: { headline: "The Abstraction We Serve", summary: "An abstract concept representing the flow of debt-money, which we are told we must serve. This inverts reality: a sane economy should serve human well-being, not demand its sacrifice.", defense: "System Defense: Naturalized as if it were a force of nature. This rhetoric ('the economy demands...') removes human agency and hides the fact that it is a set of man-made rules that can be changed." } },
                    { term: "media", explanations: { headline: "Manufacturing Consent", summary: "A corporate-owned narrative machine that distracts with spectacle and divides with culture wars to prevent the public from questioning the foundational economic system.", defense: "System Defense: Protected by the ideal of a 'free press.' This ignores that ownership by a handful of corporations, all part of the same financial system, creates a powerful incentive to protect that system from scrutiny." } },
                    { term: "consumer", explanations: { headline: "The Citizen, Commodified", summary: "The reframing of a human being from an active citizen into a passive vessel for consumption, whose primary civic duty is to take on debt to fuel 'economic growth'.", defense: "System Defense: Celebrated as 'consumer choice' and freedom. This reframes a duty (you must consume to keep the system growing) as a privilege, hiding the lack of freedom from the system itself." } },
                    { term: "education", explanations: { headline: "The Compliance Engine", summary: "The primary function of the modern education system: to produce compliant, specialized workers and indebted consumers, rather than liberated, critical thinkers who might challenge the system.", defense: "System Defense: Justified as 'preparing students for the job market.' This presents the needs of the system as the primary goal of human development, rather than human development being the goal of the system." } },
                    { term: "conspiracy", explanations: { headline: "The Thought-Terminating Weapon", summary: "The system's rhetorical self-defense. This word is deployed to ridicule and dismiss any rational analysis of its foundational rules, conflating systemic critique with paranoia to shut down debate.", defense: "System Defense: Its power lies in social proof. By labeling a critique a 'conspiracy,' it signals to others that the idea is socially unacceptable to consider, effectively outsourcing censorship to the public itself." } }
                ]
            },
            personal: {
                name: "Personal & Relational",
                words: [
                    { term: "anxiety", explanations: { headline: "A Rational Response", summary: "The logical psychological state that results from living in a system of constant precarity, mandated competition, and information overload. It is a symptom of the environment, not a personal failing.", defense: "System Defense: Medicalized and individualized. By treating it as a personal chemical imbalance, the system avoids any inquiry into the environmental causes of the distress, turning a systemic problem into a personal one to be 'fixed' with pharmaceuticals." } },
                    { term: "stress", explanations: { headline: "System Friction", summary: "The physical and mental toll of trying to keep up with the impossible demands of the 'Competition Trap' and the constant pressure to service debt.", defense: "System Defense: Normalized as a feature of 'modern life' or a sign of personal ambition. This reframes a systemic symptom as a status symbol, encouraging people to wear their own exploitation as a badge of honor." } },
                    { term: "house", explanations: { headline: "A Financialized Human Need", summary: "A basic need for shelter, transformed by financialization into the primary vehicle for generational debt and a speculative asset for the wealthy.", defense: "System Defense: Portrayed as 'the American dream' and the primary way to 'build wealth.' This locks people into a lifetime of debt servitude in pursuit of a basic need that has been turned into a financial instrument." } },
                    { term: "freedom", explanations: { headline: "The Freedom to Choose Your Creditor", summary: "The system's redefinition of liberty. It is not freedom from the system, but the consumer 'choice' between different brands of jobs, debts, and distractions within the mandatory game.", defense: "System Defense: Conflated with consumer choice. The vast array of products and lifestyles available for purchase creates an illusion of freedom that masks the fundamental lack of freedom from the underlying debt-based imperative." } }
                ]
            }
        }
    };
    
    // --- DATA PREPARATION ---
    let flatDictionary = [];
    let termToCategoryMap = {};
    for (const categoryKey in config.dictionary) {
        const category = config.dictionary[categoryKey];
        category.words.forEach(item => {
            const primaryTerm = item.primaryTerm || item.term;
            const terms = item.terms || [item.term];
            const enrichedItem = { ...item, primaryTerm, category };
            flatDictionary.push(enrichedItem);
            terms.forEach(t => termToCategoryMap[t.toLowerCase()] = categoryKey);
        });
    }
    
    // --- CORE LOGIC ---
    function main() {
        if (document.getElementById('usurpia-panel')) return;
        injectStyles();
        const popup = createPopup();
        createControlPanel();
        setupPopupEventListeners(popup);
        if (document.getElementById('usurpia-master-toggle').checked) runAnalysis();
    }

    function runAnalysis() {
        cleanupHighlights();
        const activeMode = document.querySelector('input[name="usurpia-analysis-mode"]:checked').value;
        const activeCategories = getActiveCategories(activeMode);
        highlightKeywords(config.settings.maxHighlights, activeCategories);
    }
    
    function cleanupHighlights() {
        const highlights = document.querySelectorAll('.usurpia-highlight');
        highlights.forEach(span => {
            const parent = span.parentNode;
            parent.replaceChild(document.createTextNode(span.textContent), span);
            parent.normalize();
        });
    }

    function getActiveCategories(mode) {
        if (mode === 'engine') return ['core'];
        if (mode === 'institutions') return ['core', 'institutional'];
        if (mode === 'full') return ['core', 'institutional', 'societal', 'personal'];
        return [];
    }

    function createControlPanel() {
        const panel = document.createElement('div');
        panel.id = 'usurpia-panel';
        panel.innerHTML = `
            <div id="usurpia-panel-header">Usurpia Lens v2.6</div>
            <div><label><input type="checkbox" id="usurpia-master-toggle" checked> <strong>Lens Enabled</strong></label></div>
            <div class="usurpia-control-group">
                <label for="usurpia-density-slider">Highlight Density: <span id="usurpia-density-value">${config.settings.maxHighlights}</span></label>
                <input type="range" id="usurpia-density-slider" min="1" max="50" value="${config.settings.maxHighlights}">
            </div>
            <div class="usurpia-control-group">
                <strong>Analysis Mode:</strong>
                <label><input type="radio" name="usurpia-analysis-mode" value="engine" ${config.settings.initialAnalysisMode === 'engine' ? 'checked' : ''}> Engine Only</label>
                <label><input type="radio" name="usurpia-analysis-mode" value="institutions" ${config.settings.initialAnalysisMode === 'institutions' ? 'checked' : ''}> + Institutions</label>
                <label><input type="radio" name="usurpia-analysis-mode" value="full" ${config.settings.initialAnalysisMode === 'full' ? 'checked' : ''}> Full Spectrum</label>
            </div>
            <div class="usurpia-control-group">
                <strong>Advanced:</strong>
                <label><input type="checkbox" id="usurpia-dialectic-toggle" ${config.settings.initialDialecticMode ? 'checked' : ''}> Dialectic Mode</label>
            </div>
        `;
        document.body.appendChild(panel);

        // Event Listeners for Panel
        const masterToggle = document.getElementById('usurpia-master-toggle');
        const densitySlider = document.getElementById('usurpia-density-slider');
        const analysisModes = document.querySelectorAll('input[name="usurpia-analysis-mode"]');
        
        masterToggle.addEventListener('change', () => {
            document.body.classList.toggle('usurpia-active', masterToggle.checked);
            if (masterToggle.checked) runAnalysis(); else cleanupHighlights();
        });

        densitySlider.addEventListener('input', e => { document.getElementById('usurpia-density-value').textContent = e.target.value; });
        densitySlider.addEventListener('change', e => {
            config.settings.maxHighlights = parseInt(e.target.value, 10);
            if (masterToggle.checked) runAnalysis();
        });

        analysisModes.forEach(radio => radio.addEventListener('change', () => { if (masterToggle.checked) runAnalysis(); }));
    }

    function setupPopupEventListeners(popup) {
        document.body.addEventListener('mouseover', e => {
            if (e.target.classList.contains('usurpia-highlight')) {
                const primaryTerm = e.target.getAttribute('data-term');
                const wordData = flatDictionary.find(w => w.primaryTerm === primaryTerm);
                if (wordData) {
                    let popupHTML = `<p><strong>${wordData.explanations.headline}:</strong> ${wordData.explanations.summary}</p>`;
                    if (document.getElementById('usurpia-dialectic-toggle').checked && wordData.explanations.defense) {
                        popupHTML += `<div class="usurpia-defense"><p><strong>System Defense:</strong> ${wordData.explanations.defense}</p></div>`;
                    }
                    popup.innerHTML = popupHTML;
                    popup.style.display = 'block';
                    positionPopup(e, popup);
                }
            }
        });
        // Simplified mouseout logic
        document.body.addEventListener('mouseout', e => {
            if (e.target.classList.contains('usurpia-highlight') && !popup.matches(':hover')) {
                popup.style.display = 'none';
            }
        });
        popup.addEventListener('mouseleave', () => { popup.style.display = 'none'; });
    }

    // --- UTILITY FUNCTIONS (Styles, Highlighting, etc.) ---
    function injectStyles() {
        const style = document.createElement('style'); style.id = 'usurpia-styles';
        style.innerHTML = `
            body:not(.usurpia-active) #usurpia-panel, body:not(.usurpia-active) .usurpia-highlight, body:not(.usurpia-active) #usurpia-popup { display: none !important; }
            .usurpia-highlight { background-color: #FFFFAA !important; color: #000 !important; cursor: help; }
            #usurpia-popup { position: fixed; display: none; width: 280px; background: #fff; border: 1px solid #ccc; border-radius: 5px; box-shadow: 0 4px 12px rgba(0,0,0,0.2); padding: 15px; font-family: sans-serif; font-size: 14px; line-height: 1.5; z-index: 999999999; }
            #usurpia-popup p { margin: 0 0 10px 0; }
            .usurpia-defense { margin-top: 10px; padding-top: 10px; border-top: 1px dashed #ccc; background: #f7f7f7; padding: 10px; border-radius: 4px;}
            .usurpia-defense p { margin: 0; color: #444; }
            #usurpia-panel { position: fixed; bottom: 20px; left: 20px; background: #f0f0f0; border: 1px solid #ccc; border-radius: 8px; box-shadow: 0 4px 15px rgba(0,0,0,0.3); z-index: 1000000000; padding: 15px; font-family: sans-serif; font-size: 12px; }
            #usurpia-panel-header { text-align: center; font-weight: bold; margin-bottom: 10px; }
            #usurpia-panel label { display: block; margin: 5px 0; user-select: none; }
            #usurpia-panel .usurpia-control-group { border-top: 1px solid #ddd; padding-top: 10px; margin-top: 10px; }
        `;
        document.head.appendChild(style);
    }
    
    function createPopup() { let p = document.createElement('div'); p.id = 'usurpia-popup'; document.body.appendChild(p); return p; }
    
    function highlightKeywords(maxHighlights, activeCategories) {
        const termsToHighlight = flatDictionary.filter(d => activeCategories.includes(d.category));
        if (termsToHighlight.length === 0) return;

        const termStrings = [...new Set(termsToHighlight.flatMap(d => d.terms || [d.term]))];
        const masterRegex = new RegExp(`\\b(${termStrings.join('|')})\\b`, 'gi');
        
        const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
            acceptNode: node => (node.parentElement.tagName.match(/^(SCRIPT|STYLE|TEXTAREA|INPUT|SELECT|A)$/i) || node.parentElement.closest('#usurpia-panel')) ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT
        });

        let textNodes = [];
        while(walker.nextNode()) textNodes.push(walker.currentNode);

        textNodes.forEach(node => {
            const matches = [...node.nodeValue.matchAll(masterRegex)];
            if(matches.length === 0) return;
            
            const parent = node.parentNode;
            let lastIndex = 0;
            matches.forEach(match => {
                const foundTerm = match[0];
                const entry = flatDictionary.find(d => (d.terms || [d.term]).some(t => t.toLowerCase() === foundTerm.toLowerCase()));
                if(!entry) return;

                const offset = match.index;
                if (offset > lastIndex) {
                    parent.insertBefore(document.createTextNode(node.nodeValue.substring(lastIndex, offset)), node);
                }
                const span = document.createElement('span');
                span.className = 'usurpia-highlight';
                span.setAttribute('data-term', entry.primaryTerm);
                span.textContent = foundTerm;
                parent.insertBefore(span, node);
                lastIndex = offset + foundTerm.length;
            });
            if (lastIndex < node.nodeValue.length) {
                parent.insertBefore(document.createTextNode(node.nodeValue.substring(lastIndex)), node);
            }
            parent.removeChild(node);
        });
    }

    function positionPopup(event, popup) { /* Standard positioning logic */ let x = event.clientX + 10, y = event.clientY + 10; if (x + popup.offsetWidth > window.innerWidth) x = event.clientX - popup.offsetWidth - 10; if (y + popup.offsetHeight > window.innerHeight) y = event.clientY - popup.offsetHeight - 10; popup.style.left = `${x}px`; popup.style.top = `${y}px`; }

    main();

})();
